apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        #image: laks-narasimman/todo-app:build-33
        image: rlncts/todo-app:build-33
        ports:
        - containerPort: 80
